index.Rmd
=> trying an edit PR

01-hello.Rmd, index.Rmd
Short error example, pointers to sp/rgdal equivalents, right-assigns in pipes.
=> Ch 1 deeper changes

03-Geometries.Rmd, 04-Raster-Cube.Rmd
One comment - some small changes. Comment FIXME line 137 - add tabulation of SF and sp classes. Is this also the place to say that sp does not have a POINT, so uses a fast matrix, rather than sf using n vectors? Is that mentioned later?
=> changes in ch 3

06-Attributes.Rmd, 07-ReferenceSystems.Rmd
Typos and three FIXME comments:
6 should we mention the geometry invalidity problem here, as it is often found when carrying out intersection operations?
6 do we need references to your "meaningful" article, and to area-weighted interpolation articles?
7 do we need to distinguish WKT1 and WKT2 with regard to form and treatment of authority - do we need to foreshadow the new SQLite-based systems?
=> ch 6-7 comments

08-Plotting.Rmd, 09-BasePlot.Rmd, 13-PointPattern.Rmd
Class intervals in 8, combining base and grid in 9; in 13 question about sf -> spatstat coercion
=> ideas 8, 9, 13

index.Rmd
one typo, others challenge available data and support. Cressie's Gaul is no longer in three parts (Bayesian PP is lattice, INLA mesh is lattice, MRFs are much more present now than ten years ago, I think.
=> suggested intro changes

08-Plotting.Rmd
Also a test PR in order to show how to contribute to this repo
=> Tiny comma addition

.gitignore, packages.bib, sdsr.Rproj
And add to .gitignore
Aim: make it accessible for people using RStudio who clone the repo
=> Tidy up RStudio project-related files

17-Areal.Rmd, book.bib
I've revised 17 initially, but don't know if it is much shorter, as I haven't tried to build it. It also uses the new **rgeoda** in the last paragraph. Please let me know if there is still too much needing to be cut.
=> revised 17 first cut

03-Geometries.Rmd
Dimensionally Extended 9-Intersection Model (DE-9IM)
=> Fix typo in Exercises

06-Cubes.Rmd
=> Some small corrections in 06-Cubes.Rmd

08-Large.Rmd
=> Some small corrections in 08-Large.Rmd

01-hello.Rmd, 02-Spaces.Rmd
Dear @edzer,
I just started reading **sdsr** and have been making small changes to the source text. In this PR, you can find modifications for the first two chapters - they are mostly related to improve text consistency and fix typos. 
I also find two additional issues: (1) Section `\@ref(axisorder)` does not exist, but it is called two times in your book, and (2) some code chunks (for example, in chapter 2) have `echo=!knitr::is_latex_output()`, however, I would assume you want to have them in the paper version of the book.
Additionally, I have one question - what are the "insides and outsides of polygons" (https://keen-swartz-3146c4.netlify.app/cs.html#bounded)? I was unable to understand this from the text.
Let me know if this is useful for you. If so, I will try to create similar PRs …
=> Small changes to ch1 and ch2

07-Introsf.Rmd, 08-Large.Rmd, 09-Plotting.Rmd
Additional comments:
1. You mention `st_set_geometry(nc, NULL)` in this chapter - why not showing st_drop_geometry() instead?
2. There is a section called "Extracting point samples, aggregating", but there is no mention of aggregation
3. There is an empty section "GDAL utils"
4. There are a few warnings in this chapter:
```
```
=> adds small changes to ch7

10-Models.Rmd, 13-PointPattern.Rmd
One additional comment: not all parameters in the second equation in chapter are explained. Maybe it would be useful for readers to describe all of them.
=> Small changes to ch10 and ch11

14-Interpolation.Rmd, 16-Geostatistics.Rmd, 17-Areal.Rmd, 18-SpatialRegression.Rmd, 30-sp-raster.Rmd
One additional comment: there is a spurious (?) message in both chapters related to plotting the data - `"# Coordinate system already present. Adding new coordinate system, which will replace the existing one."`.
=> Small changes to ch12 and ch13

30-sp-raster.Rmd
Reformulate sentence to make it clearer
Thanks a lot for the book. Great work.
=> Reformulate sentence

01-hello.qmd, 02-Spaces.qmd, 03-Geometries.qmd, 08-Plotting.qmd, 09-Large.qmd, 10-Models.qmd, 12-Interpolation.qmd, 14-Areal.qmd, 15-Measures.qmd, 16-SpatialRegression.qmd, 17-Econometrics.qmd, all.bib, part-2.qmd, part-3.qmd, sp-raster.qmd
=> proofs 221015

16-SpatialRegression.qmd
Just adding the `round()` fix for ch 16.
=> add round(x, 8) in ch16

01-hello.qmd
=> Revert "Suriyahgit python"

02-Spaces.qmd, 03-Geometries.qmd, 04-Spherical.qmd, 07-Introsf.qmd, 08-Plotting.qmd
Adding python code lines for chapter-2 as tabset
=> Updating Python Codelines as tabset

14-Areal.qmd
Have tried to fix the two points in ch. 14.
=> ch 14 done

06-Cubes.qmd
I had forgotten what it was since page 14
=> Index NetCDF

07-Introsf.qmd
=> Use a dash for WKT-2
